# Generated by Django 5.2 on 2025-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=1000)),
                ('activity_code', models.CharField(max_length=100)),
                ('id_search', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city_code', models.CharField(max_length=100)),
                ('city_desc', models.CharField(max_length=1000)),
                ('capture_date', models.DateTimeField(blank=True, null=True)),
                ('capture_x', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('capture_y', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('event_user_name', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_name', models.CharField(max_length=1000)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_x', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('event_y', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit_x', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_edit_y', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_edit_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Common data',
                'verbose_name_plural': 'Common data',
                'db_table': 'commondata',
            },
        ),
    ]
